### PR TITLE
Include MIT `LICENSE` file in packaged release

### PR DESCRIPTION
**Pull request by MarijnS95**
- cargo: Simplify `include` list
- Include MIT `LICENSE` file in release
- Release 0.10.0

### CODE REVIEW

**Comment by MarijnS95** [comment]
Branch protection rules don't allow me to push `cargo-release`'s `Release 0.10.0` commit to `main`, and by extent neither the tag. Who knows, once this is merged I can hopefully push the tag pointing to a signed commit reachable on main at least!

**Comment by Jasper-Bekkers** [comment]
I just released 0.10 but didn't include this, needs to gi into 0.11

**Comment by MarijnS95** [comment]
No hurry to get 0.11 out _just_ to include the file :grimacing: (but feel free to publish a `0.10.1` with this, it's _not_ breaking!).

**Comment by Jasper-Bekkers** [comment]
> No hurry to get 0.11 out _just_ to include the file :grimacing: (but feel free to publish a `0.10.1` with this, it's _not_ breaking!).

Made it so the publish workflow works, so feel free to try it out 😄

**Comment by MarijnS95** [comment]
@Jasper-Bekkers Sure! If you can approve this PR and the clippy one so that I can merge them, I'll try it out!

**Review by Jasper-Bekkers — APPROVED** [review]

**Comment by MarijnS95** [comment]
@Jasper-Bekkers Sadly, noupe:

```
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: error: At least 1 approving review is required by reviewers with write access. 2 of 2 required status checks are expected.
To github.com:Traverse-Research/hassle-rs.git
 ! [remote rejected] main -> main (protected branch hook declined)
 ! [remote rejected] 0.10.1 -> 0.10.1 (atomic transaction failed)
error: failed to push some refs to 'github.com:Traverse-Research/hassle-rs.git'
```

**Pull request merged**
