### PR TITLE
Allow `libloading` v0.7 and v0.8

### PR DESCRIPTION
**Pull request by daxpedda**
The only relevant change in v0.8 is the migration to `windows-sys`: https://docs.rs/libloading/0.8.0/libloading/changelog/r0_8_0/index.html.

This is done in the same spirit as https://github.com/gfx-rs/wgpu/pull/3711 because I heard Mozilla, who is using `wgpu`, isn't ready to migrate to `windows-sys` yet, see https://github.com/gfx-rs/wgpu/issues/3207.

`d3d12` did this as well: https://github.com/gfx-rs/d3d12-rs/pull/43.

Originally coming from here: https://github.com/Traverse-Research/hassle-rs/pull/67#discussion_r1222169498.

### CODE REVIEW

**Comment by Elabajaba** [comment]
I'm not sure if this is necessary for wgpu, since hassle-rs is behind an optional feature that afaik mozilla doesn't enable.

**Comment by cwfitzgerald** [comment]
Either way, hassle-rs brings windows into the dep tree, so until moz figures out windows-rs, we can't use fully depend on hassle-rs. I would vote this as unnecessary.

**Comment by daxpedda** [comment]
Alright, thanks!

**Comment by MarijnS95** [comment]
> Either way, hassle-rs brings windows into the dep tree

@cwfitzgerald where does it bring this in (prior to #67) exactly? Searching for `windows` in `Cargo.lock` only shows the `winapi` crates.

**Comment by cwfitzgerald** [comment]
You know what, I just totally confused hassle-rs for gpu-allocator 🤦🏻‍♂️

Let's re-open and merge this.

**Review by Jasper-Bekkers — APPROVED** [review]

**Review by MarijnS95 — APPROVED** [review]
Approving, though I hope we're migrating _away_ from `winapi` now :wink:

**Comment by MarijnS95** [comment]
@cwfitzgerald if we ever were to use `windows` directly in this crate it'd have to be the main/core crate for COM interoperability.

**Comment by cwfitzgerald** [comment]
Yeah now that I'm putting it all together, this doesn't matter:

- libloading is only using windows-sys, which is allowed anyway.
- Mozilla is never going to use DXC, and hassle-rs never shows up in mozilla's dep tree due to it being behind a feature flag in wgpu.

I think I got hassle-rs and gpu-allocator confused again

**Pull request merged**
